// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Orion.DataAccess.DataBase;

namespace Orion.DataAccess.Migrations
{
    [DbContext(typeof(GlobalDbContext))]
    [Migration("20221102001143_mig-07")]
    partial class mig07
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Orion.Domain.Entity.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Contact");

                    b.Property<string>("Contractor");

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("Engineer");

                    b.Property<string>("Location");

                    b.Property<string>("Name");

                    b.Property<string>("Notes");

                    b.Property<int>("Number");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Orion.Domain.Entity.Quote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ItemAirCooledChillersName");

                    b.Property<string>("ItemPumpsName");

                    b.Property<string>("ItemUnitsName");

                    b.Property<string>("ItemVfdsName");

                    b.Property<string>("Name");

                    b.Property<int>("ProjectId");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Quotes");
                });

            modelBuilder.Entity("Orion.Domain.Entity.Spec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("TitleId");

                    b.HasKey("Id");

                    b.HasIndex("TitleId");

                    b.ToTable("Specs");
                });

            modelBuilder.Entity("Orion.Domain.Entity.Title", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CatalogAirCooledChillerId");

                    b.Property<int?>("CatalogPumpId");

                    b.Property<int?>("CatalogUnitId");

                    b.Property<int?>("CatalogVfdId");

                    b.Property<int?>("ItemAirCooledChillerId");

                    b.Property<int?>("ItemPumpId");

                    b.Property<int?>("ItemUnitId");

                    b.Property<int?>("ItemVfdId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("CatalogAirCooledChillerId");

                    b.HasIndex("CatalogPumpId");

                    b.HasIndex("CatalogUnitId");

                    b.HasIndex("CatalogVfdId");

                    b.HasIndex("ItemAirCooledChillerId");

                    b.HasIndex("ItemPumpId");

                    b.HasIndex("ItemUnitId");

                    b.HasIndex("ItemVfdId");

                    b.ToTable("Titles");
                });

            modelBuilder.Entity("Orion.Domain.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LoginName");

                    b.Property<string>("Name");

                    b.Property<string>("PassKey");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Orion.Domain.EntityCatalog.CatalogAirCooledChiller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Ambient");

                    b.Property<string>("ChwEwtLwt");

                    b.Property<double>("ChwGpm");

                    b.Property<string>("Model");

                    b.Property<double>("NominalCapacity");

                    b.Property<string>("Voltage");

                    b.HasKey("Id");

                    b.ToTable("CatalogAirCooledChillers");
                });

            modelBuilder.Entity("Orion.Domain.EntityCatalog.CatalogPump", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Flow");

                    b.Property<double>("Head");

                    b.Property<string>("Model");

                    b.Property<string>("Motor");

                    b.Property<double>("hp");

                    b.HasKey("Id");

                    b.ToTable("CatalogPumps");
                });

            modelBuilder.Entity("Orion.Domain.EntityCatalog.CatalogUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Cfm");

                    b.Property<string>("Model");

                    b.Property<string>("Voltage");

                    b.HasKey("Id");

                    b.ToTable("CatalogUnits");
                });

            modelBuilder.Entity("Orion.Domain.EntityCatalog.CatalogVfd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Enclosure");

                    b.Property<double>("Hp");

                    b.Property<string>("Model");

                    b.Property<string>("Voltage");

                    b.HasKey("Id");

                    b.ToTable("CatalogVfds");
                });

            modelBuilder.Entity("Orion.Domain.EntityItem.ItemAirCooledChiller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CatalogAirCooledChillerId")
                        .HasColumnName("ItemAirCooledChiller_CatalogAirCooledChillerId");

                    b.Property<int?>("CatalogId")
                        .HasColumnName("CatalogAirCooledChillerId");

                    b.Property<int>("DesignIndex");

                    b.Property<bool>("IsExcluded");

                    b.Property<int>("Quantity");

                    b.Property<int>("QuoteId");

                    b.Property<string>("Tag");

                    b.HasKey("Id");

                    b.HasIndex("CatalogAirCooledChillerId");

                    b.HasIndex("QuoteId");

                    b.ToTable("ItemAirCooledChillers");
                });

            modelBuilder.Entity("Orion.Domain.EntityItem.ItemPump", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CatalogId");

                    b.Property<int?>("CatalogPumpId");

                    b.Property<int>("DesignIndex");

                    b.Property<bool>("IsExcluded");

                    b.Property<int>("Quantity");

                    b.Property<int>("QuoteId");

                    b.Property<string>("Tag");

                    b.HasKey("Id");

                    b.HasIndex("CatalogPumpId");

                    b.HasIndex("QuoteId");

                    b.ToTable("ItemPumps");
                });

            modelBuilder.Entity("Orion.Domain.EntityItem.ItemUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CatalogId");

                    b.Property<int?>("CatalogUnitId");

                    b.Property<int>("DesignIndex");

                    b.Property<bool>("IsExcluded");

                    b.Property<int>("Quantity");

                    b.Property<int>("QuoteId");

                    b.Property<string>("Tag");

                    b.HasKey("Id");

                    b.HasIndex("CatalogUnitId");

                    b.HasIndex("QuoteId");

                    b.ToTable("ItemUnits");
                });

            modelBuilder.Entity("Orion.Domain.EntityItem.ItemVfd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CatalogId");

                    b.Property<int?>("CatalogVfdId");

                    b.Property<int>("DesignIndex");

                    b.Property<bool>("IsExcluded");

                    b.Property<int>("Quantity");

                    b.Property<int>("QuoteId");

                    b.Property<string>("Tag");

                    b.HasKey("Id");

                    b.HasIndex("CatalogVfdId");

                    b.HasIndex("QuoteId");

                    b.ToTable("ItemVfds");
                });

            modelBuilder.Entity("Orion.Domain.Entity.Project", b =>
                {
                    b.HasOne("Orion.Domain.Entity.User", "User")
                        .WithMany("Projects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Orion.Domain.Entity.Quote", b =>
                {
                    b.HasOne("Orion.Domain.Entity.Project", "Project")
                        .WithMany("Quotes")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Orion.Domain.Entity.Spec", b =>
                {
                    b.HasOne("Orion.Domain.Entity.Title", "Title")
                        .WithMany("Specs")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Orion.Domain.Entity.Title", b =>
                {
                    b.HasOne("Orion.Domain.EntityCatalog.CatalogAirCooledChiller", "CatalogAirCooledChiller")
                        .WithMany("Titles")
                        .HasForeignKey("CatalogAirCooledChillerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Orion.Domain.EntityCatalog.CatalogPump", "CatalogPump")
                        .WithMany("Titles")
                        .HasForeignKey("CatalogPumpId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Orion.Domain.EntityCatalog.CatalogUnit", "CatalogUnit")
                        .WithMany("Titles")
                        .HasForeignKey("CatalogUnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Orion.Domain.EntityCatalog.CatalogVfd", "CatalogVfd")
                        .WithMany("Titles")
                        .HasForeignKey("CatalogVfdId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Orion.Domain.EntityItem.ItemAirCooledChiller", "ItemAirCooledChiller")
                        .WithMany("Titles")
                        .HasForeignKey("ItemAirCooledChillerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Orion.Domain.EntityItem.ItemPump", "ItemPump")
                        .WithMany("Titles")
                        .HasForeignKey("ItemPumpId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Orion.Domain.EntityItem.ItemUnit", "ItemUnit")
                        .WithMany("Titles")
                        .HasForeignKey("ItemUnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Orion.Domain.EntityItem.ItemVfd", "ItemVfd")
                        .WithMany("Titles")
                        .HasForeignKey("ItemVfdId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Orion.Domain.EntityItem.ItemAirCooledChiller", b =>
                {
                    b.HasOne("Orion.Domain.EntityCatalog.CatalogAirCooledChiller", "CatalogAirCooledChiller")
                        .WithMany()
                        .HasForeignKey("CatalogAirCooledChillerId");

                    b.HasOne("Orion.Domain.Entity.Quote", "Quote")
                        .WithMany("ItemAirCooledChillers")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Orion.Domain.EntityItem.ItemPump", b =>
                {
                    b.HasOne("Orion.Domain.EntityCatalog.CatalogPump", "CatalogPump")
                        .WithMany()
                        .HasForeignKey("CatalogPumpId");

                    b.HasOne("Orion.Domain.Entity.Quote", "Quote")
                        .WithMany("ItemPumps")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Orion.Domain.EntityItem.ItemUnit", b =>
                {
                    b.HasOne("Orion.Domain.EntityCatalog.CatalogUnit", "CatalogUnit")
                        .WithMany()
                        .HasForeignKey("CatalogUnitId");

                    b.HasOne("Orion.Domain.Entity.Quote", "Quote")
                        .WithMany("ItemUnits")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Orion.Domain.EntityItem.ItemVfd", b =>
                {
                    b.HasOne("Orion.Domain.EntityCatalog.CatalogVfd", "CatalogVfd")
                        .WithMany()
                        .HasForeignKey("CatalogVfdId");

                    b.HasOne("Orion.Domain.Entity.Quote", "Quote")
                        .WithMany("ItemVfds")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
